{% set name = "rake_nltk" %}
{% set version = "1.0.5" %}
{% set sha256 = "d08de98ec5d2370fdb1fdc15e0ede5b8cdcf3563f13ec00e4a5c6bbf7bf15e40" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('_', '-') }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: true  # [win]

requirements:
  host:
    - python
    - pip
    - nltk
    - nltk_data
  run:
    - python
    - nltk
    - nltk_data

test:
  imports:
    - rake_nltk


about:
  home: https://github.com/csurfer/rake-nltk
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: RAKE short for Rapid Automatic Keyword Extraction algorithm

  description: |
    RAKE short for Rapid Automatic Keyword Extraction algorithm, is a domain independent
    keyword extraction algorithm which tries to determine key phrases in a body of text
    by analyzing the frequency of word appearance and its co-occurance with other words
    in the text.
  dev_url: https://github.com/csurfer/rake-nltk

extra:
  recipe-maintainers:
    - cu8blank
    - Ryan-Dmello
