appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: g1o5mxQnXiHoDiGZB7WQBP5TZLjNRTX/JT7Gl7HLjghcr0tJMWjSIFWxRFlQrR60dOF4LpHsb2OlzLSLXN9HGw1rsC7Bujj0vUUbygMuYhyHVRnFwOloK0XlSzklgf3Y0D2RhIqO2KnSEi1P3ptWDPYyLp2WXLgfvkdPS+XVJXEBh5aOLOEM6zmdtjQnS/v9dqPCrjbkxn8YZKRwqD4ZLoWx1meGefRgre6KXJazHSsH960gOwlEi+NE45/CTor+WEbuHavRQ/ExtVeIwS9oTpM+/dwkIrzsfa2eR3+q+mPdNqr3JLEk9S6sQ6w6N0ALjWj7sWvcLtYqY5O54Hlf0X1PnrVc2UTtvEcx603VrMQ5S5YnHqgnx6Yeio41GW/220LU3TdT7462SqrrlkeG5HeU0Mx+XsamXsi8bvnIai+TJxf7xrjVq0nTvYh08ly7RcFSf77PnU3bBSg7E9wsoeOVzTvnsOTVni/tXs0aTwcn798lZ0j5E0rcHjgZl+RyVUntFEAbnUzHtCACe1XIJnk1I//xsb1gjkblsqVE/RhkWT+jTskl1yzIwsiWSQ58DcNs/eslE+VbqT/smXlAUr0vuXupRCUk/fBYWBvSYwS2xun5Ugt+35Ez4q/VTWi8CoH2R+tKf1Rb78paK4fSawzErESyCJ8bVFy3gmztB4U=}
provider:
  linux_ppc64le: azure
conda_forge_output_validation: false
